export const FETCH_ITEMS_START = 'FETCH_ITEMS_START'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE'

export const LOAD_ITEMS_START = 'LOAD_ITEMS_START'
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS'
export const LOAD_ITEMS_FAILURE = 'LOAD_ITEMS_FAILURE'

export const FETCH_ITEM_BY_ID_START = 'FETCH_ITEM_BY_ID_START'
export const FETCH_ITEM_BY_ID_SUCCESS = 'FETCH_ITEM_BY_ID_SUCCESS'
export const FETCH_ITEM_BY_ID_FAILURE = 'FETCH_ITEM_BY_ID_FAILURE'

export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET'

export const SEARCH_PHONE = 'SEARCH_PHONE'

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET'
export const CLEAN_BASKET = 'CLEAN_BASKET'